
info:
  title: EWN Task Server
  description: This API is built for the EWN website.
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Localhost

paths:
  /api/auth/send-otp:
    $ref: './paths/auth.yaml#/signup'
  /api/auth/signup:
    $ref: './paths/auth.yaml#/signup'
  /api/auth/login:
    $ref: './paths/auth.yaml#/login'
  /api/otp/send:
    $ref: './paths/otp.yaml#/sendOtp'
  /api/otp/verify:
    $ref: './paths/otp.yaml#/verifyOtp'
  /api/user/profile:
    $ref: './paths/user.yaml#/userProfile'

components:
  schemas:
    $ref: './components/schemas.yaml'  # All schema definitions
